version: '3.8'

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: sevra-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - sevra-network

  certbot:
    image: certbot/certbot
    container_name: sevra-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - sevra-network

networks:
  sevra-network:
    external: true
